---
name: Pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup OpenSCAD
        uses: ./.github/actions/setup-openscad
        with:
          scadm-source: cmd/scadm

      - name: Make scripts executable
        run: chmod +x .githooks/flatten-validate

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
